DROP PROCEDURE IF EXISTS proc_download(UUID, UUID);
DROP TABLE IF EXISTS usersLoginSession;
DROP TABLE IF EXISTS jwt_blacklist;
DROP TABLE IF EXISTS download;
DROP TABLE IF EXISTS shared;
DROP TABLE IF EXISTS filestat;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";